
services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: michael
      POSTGRES_PASSWORD: localdev
      POSTGRES_DB: localdev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: michael.urian@gmail.com
      PGADMIN_DEFAULT_PASSWORD: localdev
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - pg-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  pg-network:
    driver: bridge